site_name: Lefi
site_author: an-dyy
site_description: A discord API wrapper focused on clean code, and usability

theme:
  name: material
  palette:
    - scheme: slate
      primary: pink
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
    - scheme: default
      primary: pink
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode


nav:
  - Home: index.md
  - Getting-Started: getting-started.md
  - API-Reference:
    - Client: API-Reference/client.md
    - HTTPClient: API-Reference/http.md
    - Errors: API-Reference/errors.md

plugins:
- search
- mkdocstrings:
    handlers:
      python:
        rendering:
          members_order: source
        import:
          - https://docs.python.org/3.9/objects.inv
          - https://docs.aiohttp.org/en/stable/objects.inv

repo_name: an-dyy/Lefi
repo_url: https://github.com/an-dyy/Lefi

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - admonition
