site_name: Lefi
site_author: an-dyy
site_description: A discord API wrapper focused on clean code, and usability

theme:
  name: material
  palette:
    - scheme: slate
      primary: pink
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
    - scheme: default
      primary: pink
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode


nav:
  - Home: index.md
  - Getting-Started: getting-started.md

plugins:
- search
- mkdocstrings

repo_name: an-dyy/Lefi
repo_url: https://github.com/an-dyy/Lefi

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - admonition
